#!/usr/bin/env python3
"""verify-links.py — Check link/reference integrity across the skills.

Offline checks (safe in CI, no network):
  1. depends_on: every named skill exists as .claude/skills/<name>/SKILL.md
  2. cross-skill markdown links [x](../skill-name/SKILL.md) resolve to a file
  3. wikilinks [[skill-name]] resolve to a skill directory
  4. relative references (references/, scripts/, assets/ files) exist
  5. URL structure: bare https?:// URLs are well-formed (host present, no
     spaces, no obvious truncation artifacts like trailing punctuation)

URL *status* checking is handled against the checked-in url-registry.json
(generated by scripts/refresh-url-registry.py from live HEAD/GET checks):
unregistered URLs and clear dead statuses (400/404/410) are violations. Other
non-2xx statuses are warnings because many API/auth/browser-only endpoints are
real but unverifiable by a generic offline CI check. This makes fabricated or
guessed public URLs visible in review, while keeping CI deterministic.

All of the above is offline — no network is touched in CI. The registry is
kept current by the incremental refresh (freshness rotation, see
refresh-url-registry.py) and the scheduled url-registry-refresh workflow. If
the registry is older than --max-registry-age-days (default 90), a non-fatal
warning is printed so staleness is visible instead of accumulating silently.

Usage:
    python3 scripts/verify-links.py
    python3 scripts/verify-links.py --no-url-registry   # structural checks only

Exit codes: 0 = clean, 1 = violations found.
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_SKILLS_DIR = REPO_ROOT / ".claude" / "skills"
DEFAULT_URL_REGISTRY = SCRIPT_DIR / "url-registry.json"

# Sub-skill file references that must resolve on disk.
LOCAL_REF_RE = re.compile(r"\[[^\]]*\]\(((?:\.\./)?(?:[a-z0-9_-]+/)?(?:SKILL\.md|references/[^)#]+|scripts/[^)#]+|assets/[^)#]+))\)")
WIKILINK_RE = re.compile(r"\[\[([a-z0-9_-]+)\]\]")
URL_RE = re.compile(r"https?://[^\s\)\]>'\"`]+")


def scan_file(path: Path, skills_dir: Path, url_registry: dict | None) -> list[str]:
    problems = []
    text = path.read_text()
    try:
        rel = str(path.relative_to(skills_dir.parent))  # relative to .claude/
    except ValueError:
        rel = str(path)  # external test dirs

    # --- depends_on ---
    for line in text.splitlines():
        if line.strip().startswith("depends_on:"):
            for name in re.findall(r"[a-z][a-z0-9_-]*", line.split(":", 1)[1]):
                if not (skills_dir / name / "SKILL.md").exists():
                    problems.append(f"{rel}: depends_on references missing skill '{name}'")

    # --- markdown cross-skill / local references ---
    for m in LOCAL_REF_RE.finditer(text):
        target = m.group(1)
        if target.startswith("../"):
            t = (path.parent / target).resolve()
            if not t.exists():
                problems.append(f"{rel}: broken link -> {target}")
        elif target.startswith("references/") or target.startswith("scripts/") or target.startswith("assets/"):
            t = (path.parent / target).resolve()
            if not t.exists():
                problems.append(f"{rel}: broken local reference -> {target}")
        elif target.endswith("SKILL.md"):
            t = (path.parent / target).resolve()
            if not t.exists():
                problems.append(f"{rel}: broken skill link -> {target}")

    # --- wikilinks ---
    for m in WIKILINK_RE.finditer(text):
        name = m.group(1)
        if name.startswith("sources/") or "/" in name:
            continue  # wiki-style links outside skill scope
        if not (skills_dir / name / "SKILL.md").exists():
            problems.append(f"{rel}: wikilink [[{name}]] does not match any skill")

    # --- URL structure + registry status ---
    for m in URL_RE.finditer(text):
        # cleaning must match scripts/refresh-url-registry.py exactly
        url = m.group(0).rstrip(".,;:!?*\\")
        while url.count("(") > url.count(")") and url.endswith("("):
            url = url[:-1]
        # templated URLs ({lang}.wikipedia.org), placeholder examples
        # (https://...) and localhost/dev hosts are documentation patterns,
        # not literal remote URLs — skip structural + registry checks
        if ("{" in url or "}" in url or url in ("https://", "http://")
                or url.endswith("...")):
            continue
        parsed = urlparse(url)
        host = parsed.hostname or ""
        if not host or ("." not in host and host != "localhost"
                        and not host.replace(".", "").isdigit()):
            problems.append(f"{rel}: malformed URL -> {url}")
        if " " in url:
            problems.append(f"{rel}: URL contains a space -> {url}")
        if url_registry is not None:
            if urlparse(url).hostname == "localhost":
                continue  # local dev URLs are never in the registry
            status = url_registry.get("urls", {}).get(url)
            if EXAMPLE_URL_RE.search(url) or POST_ONLY_RE.search(url):
                continue  # illustrative placeholder or POST-only endpoint
            if status is None:
                problems.append(
                    f"{rel}: URL not in url-registry (run scripts/refresh-url-registry.py) -> {url}")
            elif status in (-1, -2):
                continue  # classified as example / post-only by the refresher
            elif status == 0:
                print(f"  (warn) {rel}: URL status 0 (network/DNS/timeout; "
                      f"unverified, not proven live) -> {url}", file=sys.stderr)
            elif status in (400, 404, 410):
                problems.append(f"{rel}: URL status {status} -> {url}")
            elif status >= 400:
                print(f"  (warn) {rel}: URL status {status} (unverifiable but not "
                      f"clearly dead) -> {url}", file=sys.stderr)

    return problems


# Illustrative placeholder URLs (from the registry's skip classification)
EXAMPLE_URL_RE = re.compile(
    r"""(?:
      example\.com|example\.org|example\.jpg|doi\.org/10\.0000/example|<[A-Za-z_-]+>|\{[a-z_]+\}|
      \*\.|your-[a-z-]+|my-[a-z][a-z-]*|123456\d*|wrong-[a-z-]+|\bxxx\b|
      placeholder|\bTBD\b|library/version/file|PageName|Username|Foo\.svg|Doc\.pdf|
      He_Tingbo|/thumb/$|/800px$|/1440px$|\.\.\.|/stream/$|entity/[MQ]$|/entity/$|
      /prop/(direct/|qualifier/|statement/)?$|
      rest_v1/metrics/|rest_v1/page/.*/html$|service/lw/inference/v1/models/$|core/v1/wikipedia/en/$|
      [\\<>]|\([^)]*$|Special_MyLanguage|Special:OAuth|Book_Title|rest_v1/search/page|qlever\.(cs\.uni-freiburg\.de|dev)|/sparql$
    )"""
, re.I | re.X)
POST_ONLY_RE = re.compile(
    r"""(?: :predict$ | /item/query/ | /property/query/ | /similarity-score/ |
       /rest\.php/oauth2 | /rest\.php/oauth2/ |
       web\.archive\.org/cdx/search/cdx$ |
       api\.php\?action=(?:edit|upload|delete|move|import|login|logout|createaccount|
       watch|patrol|rollback|protect|block|emailuser|undelete|revisiondelete|
       suppression|changecontentmodel|stabilize|review) )"""
, re.I | re.X)


def load_registry(path: Path) -> dict | None:
    if not path.exists():
        return None
    return json.loads(path.read_text())


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--skills-dir", type=Path, default=DEFAULT_SKILLS_DIR)
    ap.add_argument("--url-registry", type=Path, default=DEFAULT_URL_REGISTRY)
    ap.add_argument("--no-url-registry", action="store_true",
                    help="skip URL registry cross-check (structural checks only)")
    ap.add_argument("--max-registry-age-days", type=int, default=90,
                    help="warn if url-registry.json is older than this many days "
                         "(default 90; informational, never a failure)")
    args = ap.parse_args(argv)

    url_registry = None if args.no_url_registry else load_registry(args.url_registry)

    # Registry staleness: informational only. The scheduled refresh workflow
    # keeps the registry current; this warns if that has stopped happening.
    if url_registry is not None:
        gen = url_registry.get("generated_at")
        if gen:
            try:
                generated = datetime.strptime(gen, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)
                age = (datetime.now(timezone.utc) - generated).days
                if age > args.max_registry_age_days:
                    print(f"  (warn) url-registry.json is {age} days old (>"
                          f"{args.max_registry_age_days}); run scripts/refresh-url-registry.py "
                          f"or check the scheduled refresh workflow", file=sys.stderr)
            except ValueError:
                print(f"  (warn) url-registry.json has unparseable generated_at: {gen!r}",
                      file=sys.stderr)

    all_problems = []
    # Scan every skill Markdown file, not just SKILL.md and references/*.md.
    # Asset templates and example outputs can carry URLs too, so they need the
    # same structural and registry checks.
    files = sorted(args.skills_dir.rglob("*.md"))
    for f in files:
        all_problems.extend(scan_file(f, args.skills_dir, url_registry))

    for p in all_problems:
        print(f"  x {p}")
    print(f"\n{len(files)} files scanned, {len(all_problems)} link violation(s).")

    return 1 if all_problems else 0


if __name__ == "__main__":
    sys.exit(main())
